version: '3.9'
services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    environment:
      - AMQ_USER=aboba
      - AMQ_PASSWORD=aboba
      - AMQ_PORT=${ARTEMIS_PORT}
    ports:
      - "8161:8161"
      - "${ARTEMIS_PORT}:${ARTEMIS_PORT}"
    healthcheck:
      test: "curl --silent --fail artemis:8161/console || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=aboba
      - POSTGRES_PASSWORD=aboba
      - POSTGRES_DB=nexign_bootcamp
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-volume:/var/lib/postgresql/volumes
    healthcheck:
      test: "pg_isready -d nexign_bootcamp -U aboba"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always

  server-config:
    build:
      context: server-config
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-server-config
    ports:
      - "${SERVER_CONFIG_PORT}:${SERVER_CONFIG_PORT}"
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail server-config:${SERVER_CONFIG_PORT}/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always

  crm:
    build:
      context: crm
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-crm
    ports:
      - "${CRM_PORT}:${CRM_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      artemis:
        condition: service_healthy
      server-config:
        condition: service_healthy
      brt:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail crm:${CRM_PORT}/crm/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always

  brt:
    build:
      context: brt
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-brt
    ports:
      - "${BRT_PORT}:${BRT_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      artemis:
        condition: service_healthy
      server-config:
        condition: service_healthy
      hrs:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail brt:${BRT_PORT}/brt/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always
    volumes:
      - ./files:/home/files

  hrs:
    build:
      context: hrs
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-hrs
    ports:
      - "${HRS_PORT}:${HRS_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      artemis:
        condition: service_healthy
      server-config:
        condition: service_healthy
      data-gen:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail hrs:${HRS_PORT}/hrs/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always
    volumes:
      - ./files:/home/files

  data-gen:
    build:
      context: data-gen
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-data-gen
    ports:
      - "${DATA_GEN_PORT}:${DATA_GEN_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      server-config:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail data-gen:${DATA_GEN_PORT}/data-gen/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdr-network
    restart: always
    volumes:
      - ./files:/home/files

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    image: thatdraenguy/nexign-bootcamp-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      server-config:
        condition: service_healthy
      crm:
        condition: service_healthy
      data-gen:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: "curl --silent --fail gateway:${GATEWAY_PORT}/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      cdr-network:
        ipv4_address: 172.25.0.101
    restart: always

networks:
  cdr-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24